apiVersion: v1
kind: Service
metadata:
  name: contributions-tracker-service
  namespace: contributions-tracker
spec:
  type: ClusterIP
  selector:
    app: contributions-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
