apiVersion: v1
kind: Service
metadata:
  name: contributions-tracker-service
  namespace: contributions-tracker
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: 'nlb'
spec:
  selector:
    app: contributions-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
